name: Release

on:
  workflow_dispatch:
    inputs:
      nuget:
        #description: 'Pororoca.Test NuGet'
        required: true
        default: true
        type: boolean
      enableDesktopUITesting:
        required: true
        default: false
        type: boolean
      linux-x64:
        required: true
        default: true
        type: boolean
      osx-x64:
        required: true
        default: true
        type: boolean
      osx-arm64:
        required: true
        default: true
        type: boolean
      win-x64-installer:
        required: true
        default: true
        type: boolean
      win-x64-portable:
        required: true
        default: true
        type: boolean
      win-x86-installer:
        required: true
        default: true
        type: boolean
      win-x86-portable:
        required: true
        default: true
        type: boolean

jobs:
  nuget:
    if: ${{ inputs.nuget }}
    uses: ./.github/workflows/generate-pororoca-test-nuget-wfw.yml
  linux-x64:
    if: ${{ inputs.linux-x64 }}
    uses: ./.github/workflows/generate-desktop-release-wfw.yml
    with:
      os: ubuntu-latest
      rid: linux-x64
      enableUITesting: ${{ inputs.enableDesktopUITesting }}
  osx-x64:
    if: ${{ inputs.osx-x64 }}
    uses: ./.github/workflows/generate-desktop-release-wfw.yml
    with:
      os: ubuntu-latest
      rid: osx-x64
      enableUITesting: ${{ inputs.enableDesktopUITesting }}
  osx-arm64:
    if: ${{ inputs.osx-arm64 }}
    uses: ./.github/workflows/generate-desktop-release-wfw.yml
    with:
      os: ubuntu-latest
      rid: osx-arm64
      enableUITesting: ${{ inputs.enableDesktopUITesting }}
  win-x64-installer:
    if: ${{ inputs.win-x64-installer }}
    uses: ./.github/workflows/generate-desktop-release-wfw.yml
    with:
      os: windows-latest
      rid: win-x64
      installation: withInstaller
      enableUITesting: ${{ inputs.enableDesktopUITesting }}
  win-x64-portable:
    if: ${{ inputs.win-x64-portable }}
    uses: ./.github/workflows/generate-desktop-release-wfw.yml
    with:
      os: windows-latest
      rid: win-x64
      installation: portable
      enableUITesting: ${{ inputs.enableDesktopUITesting }}
  win-x86-installer:
    if: ${{ inputs.win-x86-installer }}
    uses: ./.github/workflows/generate-desktop-release-wfw.yml
    with:
      os: windows-latest
      rid: win-x86
      installation: withInstaller
      enableUITesting: ${{ inputs.enableDesktopUITesting }}
  win-x86-portable:
    if: ${{ inputs.win-x86-portable }}
    uses: ./.github/workflows/generate-desktop-release-wfw.yml
    with:
      os: windows-latest
      rid: win-x86
      installation: portable
      enableUITesting: ${{ inputs.enableDesktopUITesting }}
