name: Generate Pororoca.Test NuGet

on:
  workflow_call:

jobs:

  generatePororocaTestNuget:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.403
    
    - name: Install CycloneDX SBOM tool
      run: dotnet tool install --global CycloneDX

    - name: Restore solution
      run: dotnet restore --nologo --verbosity quiet
      
    - name: Build solution
      run: dotnet build --no-restore --configuration Release --nologo --verbosity quiet

    - name: Execute unit tests
      run: dotnet test --no-build --configuration Release --nologo --verbosity quiet --filter FullyQualifiedName!~Pororoca.Test.Tests

    - name: Read package version
      shell: pwsh
      run: |
        ([XML]$nugetCsprojXml = Get-Content ./src/Pororoca.Test/Pororoca.Test.csproj)
        $versionName = $nugetCsprojXml.Project.PropertyGroup.PackageVersion
        echo "VERSION_NAME=${versionName}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
    
    - name: Generate Pororoca.Test SBOM file
      shell: pwsh
      run: dotnet CycloneDX ./src/Pororoca.Test/Pororoca.Test.csproj -o ./out/ -f sbom_pororoca_test.json -sv $env:VERSION_NAME --json
    
    - name: Generate Pororoca.Desktop SBOM file
      shell: pwsh
      run: dotnet CycloneDX ./src/Pororoca.Desktop/Pororoca.Desktop.csproj -o ./out/ -f sbom_pororoca_desktop.json -sv $env:VERSION_NAME --json
    
    - name: Pack NuGet
      run: dotnet pack ./src/Pororoca.Test/Pororoca.Test.csproj --nologo --verbosity quiet --configuration Release
          
    - name: Upload NuGet package artifact
      uses: actions/upload-artifact@v3
      with:
        path: ${{ format('./src/Pororoca.Test/bin/Release/Pororoca.Test.{0}.nupkg', env.VERSION_NAME) }}

    - name: Upload Pororoca.Desktop SBOM file artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./out/sbom_pororoca_desktop.json
    
    - name: Upload Pororoca.Test SBOM file artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./out/sbom_pororoca_test.json
