name: Generate artifacts

on:
  workflow_dispatch:
    inputs:
      nuget:
        required: true
        default: true
        type: boolean
      enableDesktopUITesting:
        required: true
        default: false
        type: boolean
      linux_x64:
        required: true
        default: true
        type: boolean
      linux_x64_debian:
        required: true
        default: true
        type: boolean
      osx:
        required: true
        default: true
        type: boolean
      # osx-arm64:
      #   required: true
      #   default: true
      #   type: boolean
      win_x64_installer:
        required: true
        default: true
        type: boolean
      win_x64_portable:
        required: true
        default: true
        type: boolean
      win_x86_installer:
        required: true
        default: true
        type: boolean
      win_x86_portable:
        required: true
        default: true
        type: boolean

jobs:
  nuget-linux-osx:
    if: ${{ inputs.nuget || inputs.linux_x64 || inputs.linux_x64_debian || inputs.osx }}
    uses: ./.github/workflows/cicd-wfw.yml
    with:
      os: ubuntu-latest
      runCD: true
      enableUITesting: ${{ inputs.enableDesktopUITesting }}
      producePororocaTestNuget: ${{ inputs.nuget }}
      produceDesktopLinuxX64: ${{ inputs.linux_x64 }}
      produceDesktopDebianX64: ${{ inputs.linux_x64_debian }}
      produceDesktopMacOSX: ${{ inputs.osx }}

  windows:
    if: ${{ inputs.win_x64_installer || inputs.win_x64_portable || inputs.win_x86_installer || inputs.win_x86_portable }}
    uses: ./.github/workflows/cicd-wfw.yml
    with:
      os: windows-latest # running on Windows because we need NSIS
      runCD: true
      enableUITesting: ${{ inputs.enableDesktopUITesting }}
      produceDesktopWinX64Installer: ${{ inputs.win_x64_installer }}
      produceDesktopWinX64Portable: ${{ inputs.win_x64_portable }}
      produceDesktopWinX86Installer: ${{ inputs.win_x86_installer }}
      produceDesktopWinX86Portable: ${{ inputs.win_x86_portable }}
