name: Generate artifacts

on:
  workflow_dispatch:
    inputs:
      nuget:
        required: true
        default: true
        type: boolean
      enableDesktopUITesting:
        required: true
        default: false
        type: boolean
      linux-x64:
        required: true
        default: true
        type: boolean
      linux-x64-debian:
        required: true
        default: true
        type: boolean
      osx:
        required: true
        default: true
        type: boolean
      # osx-arm64:
      #   required: true
      #   default: true
      #   type: boolean
      win-x64-installer:
        required: true
        default: true
        type: boolean
      win-x64-portable:
        required: true
        default: true
        type: boolean
      win-x86-installer:
        required: true
        default: true
        type: boolean
      win-x86-portable:
        required: true
        default: true
        type: boolean

jobs:
  nuget-linux-osx:
    if: ${{ inputs.nuget || inputs.linux-x64 || inputs.linux-x64-debian || inputs.osx }}
    uses: ./.github/workflows/cicd-wfw.yml
    with:
      os: ubuntu-latest
      runCD: true
      enableUITesting: ${{ inputs.enableDesktopUITesting }}
      producePororocaTestNuget: ${{ inputs.nuget }}
      produceDesktopLinuxX64: ${{ inputs.linux-x64 }}
      produceDesktopDebianX64: ${{ inputs.linux-x64-debian }}
      produceDesktopMacOSX: ${{ inputs.osx }}

  windows:
    if: ${{ inputs.win-x64-installer || inputs.win-x64-portable || inputs.win-x86-installer || inputs.win-x86-portable }}
    uses: ./.github/workflows/cicd-wfw.yml
    with:
      os: windows-latest # running on Windows because we need NSIS
      runCD: true
      enableUITesting: ${{ inputs.enableDesktopUITesting }}
      produceDesktopWinX64Installer: ${{ inputs.win-x64-installer }}
      produceDesktopWinX64Portable: ${{ inputs.win-x64-portable }}
      produceDesktopWinX86Installer: ${{ inputs.win-x86-installer }}
      produceDesktopWinX86Portable: ${{ inputs.win-x86-portable }}
